name: flashcards

services:

  db: 
    image: postgres
    ports:
      - "5432:5432"
    networks:
        - net1
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: flashcards_db
    volumes:
      - flashcards_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine # light version
    ports:
      - "${REDIS__Port}:6379"
    networks:
        - net1
    command: >
      redis-server
      --requirepass ${REDIS__Password}
      --include /etc/redis-extra.conf
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis-extra.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS__Password} ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  gatewayapi:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net1
    env_file:
      - .env
    #command: ["migrate"] # flag to start the migration process - JWT_SECRET_KEY = "test_secret_for_migrations"; Add-Migration Tokens -Project Infrastructure -StartupProject GatewayApi
    volumes:
      - ./Infrastructure/Storage/Images:/storage/images
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  net1:
    driver: bridge

volumes:
    flashcards_db_data:
    redis_data: