name: flashcards

services:

  db: 
    image: postgres
    ports:
      - "5432:5432"
    networks:
        - net1
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: flashcards_db
    volumes:
      - flashcards_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine # light version
    ports:
      - "${REDIS__Port}:6379"
    networks:
        - net1
    command: redis-server --requirepass ${REDIS__Password}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  gatewayapi:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    #ports:
    #  - "8080:8080"
    networks:
      - net1
    #command: ["migrate"] # flag to start the migration process - JWT_SECRET_KEY = "test_secret_for_migrations"; Add-Migration Tokens -Project Infrastructure -StartupProject GatewayApi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASP_ENV} 
      - ASPNETCORE_URLS=http://+:8080 # one port
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__FlashCardsConnectionString=${FLASHCARDS_DB_CONNECTION_STRING} # connection string from .env or secrets
      - API__OriginUrl=${API__OriginUrl}
      - API__LoginUrl=${API__LoginUrl}
      - API__ConfirmEmailUrlTemplate=${API__ConfirmEmailUrlTemplate}
      - REDIS__Host=${REDIS__Host}
      - REDIS__Port=${REDIS__Port}
      - REDIS__Password=${REDIS__Password}
      - REDIS__Db=${REDIS__Db}
      - REDIS__InstanceName=${REDIS__InstanceName}
      - SMTP__Host=${SMTP__Host}
      - SMTP__Port=${SMTP__Port}
      - SMTP__Account=${SMTP__Account}
      - SMTP__Password=${SMTP__Password}
      - SMTP__From=${SMTP__From}
      - FILE_STORAGE_PATH=/storage/images
    deploy:
      replicas: 4
    volumes:
      - ./Infrastructure/Storage/Images:/storage/images
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy    

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # one port for all
    networks:
      - net1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gatewayapi
    command: nginx -g "daemon off;"

networks:
  net1:
    driver: bridge

volumes:
    flashcards_db_data:
    redis_data: