name: flashcards

services:

  db: 
    image: postgres
    ports:
      - "5432:5432"
    networks:
        - net1
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: flashcards_db
    volumes:
      - flashcards_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine # light version
    ports:
      - "${REDIS_PORT}:6379"
    networks:
        - net1
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  gatewayapi:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net1
    #command: ["migrate"] # flag to start the migration process - JWT_SECRET_KEY = "test_secret_for_migrations"; Add-Migration Tokens -Project Infrastructure -StartupProject GatewayApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ConnectionStrings__FlashCardsConnectionString=${FLASHCARDS_DB_CONNECTION_STRING} # connection string from .env or secrets
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FILE_STORAGE_PATH=/storage/images
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - ./Infrastructure/Storage/Images:/storage/images
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy    

networks:
  net1:
    driver: bridge

volumes:
    flashcards_db_data:
    redis_data: